# Generated by Django 6.0.3 on 2026-03-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_fare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['order']},
        ),
    ]
