# Generated by Django 6.0.3 on 2026-03-10 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_stop_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.depot'),
        ),
    ]
