# Generated by Django 6.0.3 on 2026-03-10 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_route_depot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.depot'),
        ),
    ]
