# Generated by Django 6.0.3 on 2026-04-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_seathold_bookingreview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookingreview',
            new_name='booking_boo_user_id_92205f_idx',
            old_name='booking_boo_user_id_cb8a2f_idx',
        ),
        migrations.RenameIndex(
            model_name='bookingreview',
            new_name='booking_boo_rating_3e9ff8_idx',
            old_name='booking_boo_rating_883a74_idx',
        ),
        migrations.RenameIndex(
            model_name='seathold',
            new_name='booking_sea_bus_id_083d80_idx',
            old_name='booking_seat_bus_id_6d73f9_idx',
        ),
        migrations.RenameIndex(
            model_name='seathold',
            new_name='booking_sea_expires_2b4402_idx',
            old_name='booking_seat_expires_19f0b4_idx',
        ),
    ]
