# Generated by Django 6.0.3 on 2026-03-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_emailotp_remove_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STATION_MASTER', 'Station Master'), ('USER', 'User')], default='USER', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
