# Generated by Django 6.0.3 on 2026-03-08 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role_user_station'),
        ('transport', '0002_fare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='station',
        ),
        migrations.AddField(
            model_name='user',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.depot'),
        ),
    ]
