# Generated by Django 6.0.3 on 2026-03-09 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_tour', '0001_initial'),
        ('transport', '0003_alter_stop_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtourbooking',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_special_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialtourbooking',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.depot'),
        ),
        migrations.AddField(
            model_name='specialtourbooking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='specialtourbooking',
            name='bus_type',
            field=models.CharField(choices=[('AC', 'AC'), ('NON_AC', 'Non AC'), ('SLEEPER', 'Sleeper')], max_length=20),
        ),
        migrations.AlterField(
            model_name='specialtourbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
