# Generated by Django 6.0.3 on 2026-03-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_tour', '0002_specialtourbooking_approved_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialtourbooking',
            old_name='depot',
            new_name='assigned_depot',
        ),
        migrations.RenameField(
            model_name='specialtourbooking',
            old_name='price',
            new_name='estimated_price',
        ),
        migrations.AddField(
            model_name='specialtourbooking',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialtourbooking',
            name='bus_type',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC'), ('Sleeper', 'Sleeper')], max_length=20),
        ),
        migrations.AlterField(
            model_name='specialtourbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
