# Generated by Django 6.0.3 on 2026-03-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_tour', '0003_rename_depot_specialtourbooking_assigned_depot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtourbooking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='specialtourbooking',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
